version: '3.8'

services:
  ocr_service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./logs:/app/logs
      - ./temp_image:/app/temp_image
    restart: unless-stopped
    networks:
      - shared_network

networks:
  shared_network:
    external: true
